postgres_password_postgres: ENC[AES256_GCM,data:PVwmHEO/h+drWYcTSqQYhaQFriE=,iv:M+8i88gutzulfpffZciWvgFM0C+TdKQYUHYInI+1T5g=,tag:cJBrE4GBcHuJWE4qTJXBUw==,type:str]
postgres_password_vaultwarden: ENC[AES256_GCM,data:JeglcTrAu53hk1z1Hox4ahp9b2Y=,iv:TZyi5UyqsQeWZgQf7nCgbU40N2ZiVPKXeXKPDBxYRK4=,tag:J2jt+ffo1gUNA/6TZj3JRg==,type:str]
postgres_password_n8n: ENC[AES256_GCM,data:umUDUgnuW7dAzA2kCC3RsPPrRd0=,iv:PD0qZdoWnFMtfYkF2R9U5sVtMSXajvk3sE6Gx0kpppA=,tag:MO3YAYoTISiM1D/uJ6RXhA==,type:str]
postgres_password_misskey: ENC[AES256_GCM,data:Q9Jo3DAXIRip2+8BZejUgNuyv0E=,iv:eXPEUdDPe7wxUsUXhNGqiASNXiq6Q+grkuVkJJer7uE=,tag:aj1AS4kVg7O9hLWSshNdeA==,type:str]
postgres_backup_webhook_url: ENC[AES256_GCM,data:PitXpntcV83K48B3UBFGJzZD+IfpFZkZtZeX92lXu0glNaAqfNEMZpQSFCh3uqKHA0GTaxMdxKYHYSliGU2mnCNmrxv/vxuC/12OXVH8AyvJ57NwxdbolhT91giCqrUryTwUyn1s+9RiFY1/y1PioegYCSw7SlSZ9Q==,iv:odIzYzfyvRQjAKm+1xHidUXeH5GvYR0IhboTWoty2Cw=,tag:hun7oGChVzKLB11Enh4Tfg==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWDB6NlFVWElaa1NnUDZJ
            NDB6aFREMmVSdkZQeW5WbXpUQTNvK2VyOENJCmVRWkxxSjMwL0h1TGxDVUhmQmNh
            Y2RMa0pJWXZ0OU1FK09LRUVpb3RSNGsKLS0tIEpqbFlZaC9kZUhGWWkzS2NUQVFt
            TlFJOTd5OWljMVdpREZCcDN1M1NabVkKxkMniL8fj59XDDpI98ZrcfvugKgIkzZ2
            mXAMk3WBuMTKVD01PlPWFYnH1euge2TV6UUeBycAcGqFeZ6pxB8Qww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T15:47:34Z"
    mac: ENC[AES256_GCM,data:X4bzKcKjfLLWBiwneWXkL5MX0yr9qDBqfeky4RQL80JXS6kpkqttb25tmA7otGWQ2F4GSOItzqfbUygtIgQ219cem96vJjMNPf4Wc0shgiIxFsRqtQ1GHJLtJpIXndDw/rDqX6TMMs0epOW6P4NYAWoinv3mmPhlTGrfOVtMW2Q=,iv:gNOINWuSo9CHDHqCRV3diWDt6LQ+CwsWFQVh/GRk68Q=,tag:WkQ/HIgNynzsY/KZzdMSDA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
