postgres_password_postgres: ENC[AES256_GCM,data:0YCgXmaiioFoa41w+GrIs7jSrJc=,iv:6JcA+vyNiVPkczXlewMvRhPKW0Hb1LAzzgtk1x6kCTk=,tag:sUIqMKZvFRf1BG9q5yrTmA==,type:str]
postgres_password_vaultwarden: ENC[AES256_GCM,data:1XkswhKoNXCkRzIiSViMqD4fW2M=,iv:ZyAYGBQg9f96FYROxL39No80fXjfxXrEWIo5LYWzKxw=,tag:YKX8m+vLAVuz2eMu8b0sJQ==,type:str]
postgres_password_n8n: ENC[AES256_GCM,data:Ns9OUOK6Nf8oNyJ6cTdEeWQevRM=,iv:El9ZQ0qHAqzu/5y3tjYNw2GPdwt4C0QGHAKfkfqRyTk=,tag:S2XH92C+MLoIMGlkgV3ndw==,type:str]
postgres_password_authentik: ENC[AES256_GCM,data:2jPy9KdRKvAQkTd9+sd7FcnH0fo=,iv:Nr78guqTxW9hDbCbhPBMViOMaCUKIksOcn+16wmP1kg=,tag:cV27k3NcDwIu7J4XPpFxBA==,type:str]
postgres_password_semaphoreui: ENC[AES256_GCM,data:1rNOu8q3OOxNPk564HkMXdpmlVI=,iv:Vp0Eu077eFPH6dvo32l03bVqopqqY5ACltOulV9+M54=,tag:FlKNaKFA3KLva3BFmpMllg==,type:str]
postgres_backup_webhook_url: ENC[AES256_GCM,data:x4WmIDykyD7c5fXdwcbNLya5nhl79HOaXiQomhsCk9K4Y5sreVcMyD1pIxmDYgnGh8I1nDyGPqySNoYjlih0jMoNQt+ps3ifgkDCdOGFIdg7JVK8R+BptTJ/63GiOutRjBjzYNwAf5my9+1X2CGAkYqZcW0ZEXV0pg==,iv:xEgxRYG+ryNvBRaY3JoclW+rRq5LP2bPejX4ByDRXHM=,tag:oSctUCYVkPRb6g2tN05awA==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeUdRMFhsd2dXd0hyaWtU
            djJneVhKK3ZsMVI4NVZaV0N5MEdrV3ZrTmxFCmlTVVlhSTV0S1Y4SVN1cnhGamEx
            ZFgxWThZMk9ZOTl0c0IxbXcxWnpDUEUKLS0tIDlPQTY3elNUa1JHSFdUNTI2aTFB
            UWMvRVBDd0ZVSCtUQmlPVWtFSTNsM3MKTrR/FqVcJIXO+RFc3DNuzPBHSwTVQEV1
            Ty0U/HHGm6f35xSqi2zTk7o3S6xfsm3LZ8adfYmDN3aI2TM0l195fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T18:01:01Z"
    mac: ENC[AES256_GCM,data:v14sDB7EJ9ptRkLAPzOaru6phtLBZ1KIKQ7Rwsu4Z5Zl4AutrCFLzr15TEeDp8pDObdO7fzV93ZgN0VY48MKv1i3PFNzuJqge3Tt07J6+6bSGhK6YMxiD48k04+JjrGYl0nQULQa+IP4sC8VG7hq+eWxIJcp+J6LCTTL9UDgE+c=,iv:D5Ih1rHV65RsQBCb+m8aMeRhaBuskWTVdH5eN703HoM=,tag:A/JT2Jo1OBDkX8Em4ta/2g==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
