---
- name: Install netplan
  become: true
  ansible.builtin.apt:
    name: netplan.io
    state: present

- name: Config NIC
  become: true
  ansible.builtin.template:
    src: 51-add-vnic.yaml.j2
    dest: /etc/netplan/51-add-vnic.yaml
    owner: root
    group: root
    mode: "0600"

- name: Apply netplan
  become: true
  ansible.builtin.command:
    cmd: netplan apply
  register: oci_attach_vnic_netplan_apply
  changed_when: oci_attach_vnic_netplan_apply.stdout != ""
  failed_when: oci_attach_vnic_netplan_apply.rc != 0
